# Generated by Django 5.1 on 2024-11-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('mo_ta', models.TextField()),
                ('quy_mo', models.CharField(choices=[('Nhỏ', 'Nhỏ'), ('Vừa', 'Vừa'), ('Lớn', 'Lớn')], default='Vừa', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=250)),
                ('ngay_sinh', models.DateField()),
                ('so_dien_thoai', models.CharField(max_length=11)),
                ('gioi_thieu', models.TextField(blank=True)),
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVienDuAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhieunhanvien', to='qlduan.duan')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhieuduan', to='qlduan.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='du_an',
            field=models.ManyToManyField(through='qlduan.NhanVienDuAn', to='qlduan.duan'),
        ),
    ]
